### ISSUE TITLE
Remove IHandleRemoteMessage

### ISSUE THREAD

**Issue by mlidbom** [mlidbom/Composable#28]
**IHandleRemoteMessage**  should be removed. It is a fatally flawed routing mechanism. The idea was to get rid of duplicate handlers when the same handler was referenced in process (where the event was originally raised) and in a separate process (some other endpoint). Implementing this interface made sure that the handler was not triggered in memory so it was only executed once. But of course this fails again the second two or more endpoints references the assembly containing the handler so it is simply a broken idea.

The correct approach is to always implement bus message handlers in the assembly defining the endpoint where they should execute. Period.

**Comment by staticage** [comment]
Hi Magnus :) Maybe you could change Composable to only search handlers in the assembly of endpoint?

**Comment by mlidbom** [comment]
Hi Alex! It's been a while. 
Hope you're doing well :)

Back on topic:
That is an interesting idea. I'll need to think about the consequences of such a model.
Since I will soon be starting on removing NServiceBus from the core and implementing a built in Service Bus #8 I am currently spending a lot of time thinking about the optimal way to design the abstractions.

**Comment by staticage** [comment]
Removing NServiceBus sounds good :)

Another thought: Maybe we could check the handlers in ServiceBus.Start/Configure/Intialize and throw an exception if there is a handler not in the assembly of endpoint.

I realized that it's a problem to ignore these handler without a warning :)

**Comment by mlidbom** [comment]
Actually I think this whole issue will be removed. It seems likely that the new bus will be so different to NServiceBus that keeping old issues around will not make sense.
The more I think about it the more I believe that Composable 4 vs 3 is going to be more like Angular 2 vs 1. It will be a large enough change that existing applications will have to do some significant redesign no matter what I do. 
So I will not be attempting to achieve backwards compatibility in V4 at all. Instead I will focus on making it the best framework I can :)
