### ISSUE TITLE
Performance Suggestion

### ISSUE THREAD

**Issue by ErikRBergman** [mlidbom/Composable#47]
Since I can see you have been working on making the event sourcing in Composable perform, and I have a suggestion.

From what I can see, the domain events are created in the domain model/aggreagte constructor, every time a domain model is instantiated.

Example:
```csharp
        public Foo()
        {
            RegisterEventAppliers()
                .For<IRenamedEvent>(Apply)
                .For<IFooNamePropertyUpdated>(e => this.Name = e.Name);
        }
```
2 `Action<>` objects, 2 event registrations and a closure for ´this´ are instantiated. In a situation where a lot of domain models are instantiated, we get a lot of unnecessary allocations and GC's, especially using a domain model with a lot of events, which they tend to get over time.

Instead, i suggest event registration in a static constructor, and using the domain model as the second argument to the event handler `Action<TEvent, TDomainModel>`.

Example (Domain model/aggregate constructor):
```csharp
        static Foo()
        {
            RegisterEventAppliers()
                .For<IRenamedEvent>(Apply)
                .For<IFooNamePropertyUpdated>((theEvent, theDomainModel) => theDomainModel.Name = theEvent.Name);
        }
```
2 event registrations and 2 ´Action<,>´ objects are created, but only once. No closure is needed for the domain model, since it's a parameter.

What do you think?

**Comment by mlidbom** [comment]
Hi Erik :)
 
Thank you very much for your well thought out suggestion! 

As it happens this is something that we have put quite a lot of thought into. We have in fact considered the approach you suggest. There are a number of reasons why we have not gone that way. 


- The dispatching structure is actually neither static nor the same for all instances of the same type of an aggregate. You can nest components and collections of entities inside of an aggregate to an arbitrary depth. For each entity or component another event dispatching instance is added onto the tree of event dispatching instances that start of with the aggregate root. So as any non-trivial aggregate is populated via the events a tree of components sprout out from the root. This tree is unique to each instance.
- Keeping it non-static enables the user to add their own instance specific additions to how to route events through their aggregates.
- Our top priorities are productivity and maintainability. This means that user code simplicity coupled with flexibility is very important to us. It might be possible to achieve some level of optimization by making some dispatching code static, but doing so would likely add quite a bit of complexity to the user code as well as limit flexibility. Even your example makes things a little bit more complicated for the users. 
- The underlying code is actually quite heavily optimized already and performs quite well. It is used in many components.
- We try to always profile before optimizing to make sure that we do not spend effort where it will not pay off. And in our profiling sessions this does not appear to be significant. I've tried it with aggregates upwards of 1000 events.
  - When loading an aggregate from storage the IO totally eclipses any in-memory overhead
  - Once cached even large aggregates populate from the cached history in negligible time for user experience
  - Even when cached the latency of the round trip to the sql server to check for new events still outweighs the full time it takes to populate an aggregate from history
- Tentative future plans relevant to this
  - Stop caching the event stream and start to cache the aggregate instance instead. This should dramatically cut the memory usage for aggregates with large histories and virtually eliminate any in-memory population time.
  -  Start to have a "single active endpoint" mode for endpoints, event store, and document database. In this mode we would guarantee that only the current instance is able to make any changes to the data in the stores. Given that we will be able to eliminate the calls to storage to validate our cache. Combined with the previous item I believe that this should allow a single service instance to improve query throughput by at least an order of magnitude, and quite possibly two orders of magnitude, while perhaps doubling the rate of write transactions.



I hope this explains why I don't think we will be attempting that specific optimization.
If this seems like good reasons not to go that way to you, please close this issue. If not, feel free to disagree and let me know why. Either way, please keep making suggestions. We really do appreciate it!

**Comment by ErikRBergman** [comment]
Thank you Magnus, for a quick and very humble response :)

I must confess, I do not have that much experience with event sourcing and I did not consider many of the reasons you stated. 

- Ok, so to static constructor 2.0 :)). I'm a big fan of separation of concerns. Having one type for the aggregate and a separate type for registering and housing event handlers would to me be more logical. Having no examples to relate to (due to inexperience) one might think that when event handlers are not bound to a specific instance, they are reusable. Keeping the event registrations in immutable collections would allow customizing each instance, but it would not require it.I suppose, even with quite some customization, this would reduce the number of allocations.

- I don't think the added complexity of using non instance specific event handlers with two parameters instead of one will make life harder for many of your users, it will be perceived as more complex, when they're used to the other approach. Supporting both approaches will be a micro-performance hit, unless you group them to different dispatchers. 

- While I do not know if you purposely trigger level 2 garbage collection during your profiling sessions or you employ separate memory turnover profiling, this suggestion was never intended to be a major improvement, but a rather minor one. Based on a few incorrect assumptions about the usage.

- While I couldn't agree with you more that it requires a lot of processing to consume as time as an I/O request, there are scenarios where aggregates are instantiated and then discarded without ever being persisted. In some scenarios it is important to keep the overall resource CPU and memory consumption low or to minimize the number of GC hiccups. I wouldn't think any of these apply to your average users.

I myself is rather obsessed with writing performing code, which is why I tend to spot things in other's and my own code that I would consider experimenting with for higher performance without sacrificing architecture. I totally understand that you do not skyrocket priority of micro optimizations like these. 

If I were to focus on something, it would be to use TPL for all Event Store I/O. As of my understanding, you're already working on/considering this. While moving to using TPL for all I/O likely will be just a tad slower for an idle system with plenty of resources (your typical profiling environment), when measuring throughput on a system with some good load the difference can be huge.

Thanks
